server:
  shutdown: graceful
  port: 8090

spring:
  application:
    name: gatewayservice
  profiles:
    active: dev

logging:
  level:
    org:
      springframework: DEBUG
      reactor.netty.http.client: DEBUG