jwt:
  secret:
    key:  -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0F0LncROXoviL9c8RbcOUq7SVjb/cNal4GWW76vQStIJa8W7OuHfj+J3QJluPp1odVt4zsXJBzEYdkyoGNjMeEsxZZhyxkps5O+bcGaeWLa+D8cGJgoRV6juXV0gggcbunX1JgUgmaZ9HkQ47UFyqLHxIs0VvJnTK2Ao8Vwti7R/+TdHjaNN3ml4zXQVSCIxIUVplgEFv049j5sDH9B1Nz1Lq6hx1mN3QVajXekl0BBcKal1SxMN+P8w8Ig/ajprD3NAsV+e9SZXLDXeHH1gElKbfogSmDxzCxETCLCo9dqdZGi0MLWqFNXgMFcCTSZoDcoNtntNjm0NTfSrMm8N7QIDAQAB-----END PUBLIC KEY-----

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          predicates:
            - Path=/user/**
          uri: http://user-service:8092
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
            - name: JwtAuthenticationFilter
              args:
                secretKey: ${jwt.secret.key}

        - id: user-service-filter-excluded
          predicates:
            - Path=/users/**
          uri: http://user-service:8092
          filters:
            - RewritePath=/users/(?<segment>.*), /${segment}

        - id: token-service
          predicates:
            - Path=/token/**
          uri: http://token-service:8091
          filters:
            - RewritePath=/token/(?<segment>.*), /$\{segment}

        - id: device-service
          predicates:
            - Path=/device/**
          uri: http://device-service:8093
          filters:
            - RewritePath=/device/(?<segment>.*), /$\{segment}