jwt:
  secret:
    key: ${PUBLIC_KEY}

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          predicates:
            - Path=/user/**
          uri: http://user-service
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
            - name: JwtAuthenticationFilter
              args:
                secretKey: ${jwt.secret.key}

        - id: user-service-filter-excluded
          predicates:
            - Path=/users/**
          uri: http://user-service
          filters:
            - RewritePath=/users/(?<segment>.*), /${segment}

        - id: token-service
          predicates:
            - Path=/token/**
          uri: http://token-service
          filters:
            - RewritePath=/token/(?<segment>.*), /$\{segment}

        - id: device-service
          predicates:
            - Path=/device/**
          uri: http://device-service
          filters:
            - RewritePath=/device/(?<segment>.*), /$\{segment}